services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-go:stable-1
    init: true
    build:
      context: .
    working_dir: /app
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

